name: deploy to eks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      cluster: "eks-mundose"
      namespaces: "mundose"

    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
        with:
           version: 'v1.23.6' 
        id: install 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.cluster }} --region us-east-1
      - name: deploy to eks prueba
        run: |
          kubectl get nodes -A
          kubectl apply -f nginx-deployment.yaml -n ${{ env.namespaces }}
